# Generated by Django 4.0.3 on 2022-04-05 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulacionVivienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioMaximo', models.FloatField()),
                ('parqueadero', models.BooleanField()),
                ('distanciaAlaUniversidad', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='vivienda',
            name='distanciaAlaUniversidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transporte',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportes', to='simulacionVivienda.vivienda'),
        ),
    ]
