# Generated by Django 4.0.3 on 2022-03-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacionesPsicologos', '0002_calificacion_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='promedio_calificaciones',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
