# Generated by Django 4.0.3 on 2022-03-17 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificacionesPsicologos', '0005_psicologo_suma_calificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologo',
            name='cantidad_calificaciones',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='promedio_calificaciones',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='suma_calificaciones',
        ),
    ]
