# Generated by Django 4.0.3 on 2022-03-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacionesPsicologos', '0006_remove_psicologo_cantidad_calificaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='cantidad_calificaciones',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psicologo',
            name='promedio_calificaciones',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psicologo',
            name='suma_calificaciones',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
